version: "3"

services:
  dont-genshin-bot:
    build: .
    env_file:
      - config.env
    volumes:
      - ./appdata:/home/app/appdata
    logging:
      options:
        max-size: "1G"
        max-file: "10"
    restart: always
